services:
  db:
    image: postgres:15
    container_name: project_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    container_name: project_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
      - ../backend/media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  api:
    build: ../api
    container_name: project_api
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ../api:/app
      - ../backend:/backend 
      - ../backend/media:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app_backend.settings
      - PYTHONPATH=/backend:/app
    depends_on:
      - db
    ports:
      - "8001:8001"

  frontend:
    build: ../frontend
    container_name: project_frontend
    command: npm start
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - api

volumes:
  postgres_data: